### ISSUE TITLE
Update the documentation with a separate 'Project Setup' file

### ISSUE THREAD

**Issue by TheInspiredConjurer** [TheInspiredConjurer/Online-Questionnaire-System#4]
Currently, there are Hacktoberfest instructions on how to contribute and submit a Pull Request, but there is no documentation on how to actually setup the project for development.

Create a separate file called `Project Setup.md` in the main folder and mention detailed instructions on how to setup the project.

How you write it is upto you, but some basic requirements must be present:

- Let the reader know that they must have Node v16+ installed (LTS is good, Latest version is preferred).
- Let the reader know that they must have Python 3 installed (LTS is good, Latest version is preferred).
- Instruct the reader to setup a virtual environment and install all required Django packages inside them.

Here's a basic outline of steps that can be present in the file: -
1. Download and Install Node and Python.
2. Clone The Repo.
3. move into the `frontend` folder and build the frontend.
4. move into the `backend` folder, setup a virtual environment, and install the requirements file.
5. Run both the backend and the frontend server on different ports.

**Comment by justDabuK** [comment]
Hi @TheInspiredConjurer , 

I just saw your Discord post and your project quit matches my skills. I'd like to check it out and get it running. Since I could take notes during that and write them into a seperate file, I thought this would be a perfect first Issue. 

Could you assign me, such that don't multiple people work on it? 🤔 

Also, why would you like to have the Project Setup in a seperate file? 🤔 
I'm used to having it as a section in the README 🤔

**Comment by TheInspiredConjurer** [comment]
Hi @justDabuK Sure, go ahead!

The reason for having separate files is that I want to continue this project even after Hacktoberfest, as mentioned in the README.md.

So, it makes sense to have 2 separate files.
